# Generated by Django 5.0.6 on 2024-07-28 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_post_ratings_post_rating_times_postcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcomments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
