# Generated by Django 5.0.6 on 2024-08-15 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_postcategory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
