# Generated by Django 5.0.6 on 2024-08-18 07:58

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_postcomments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersaccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images/', validators=[myapp.models.validate_image]),
        ),
    ]
