# Generated by Django 5.0.6 on 2024-09-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_usersaccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersaccount',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
