# Generated by Django 5.0.6 on 2024-09-10 14:53

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_usersaccount_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[myapp.models.validate_title]),
        ),
    ]
