# Generated by Django 5.0.6 on 2024-10-10 09:02

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(validators=[myapp.models.validate_description]),
        ),
    ]
