name: Deploy Thunder

on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.THUNDER_DEPLOY_KEY }}

    - name: Deploy to VPS
      env:
        DJANGO_ENV: ${{ github.ref_name == 'develop' && 'qa' || github.ref_name == 'staging' && 'staging' || github.ref_name == 'main' && 'production' }}
      run: |
        SSH_HOST="${{ secrets.VPS_USER_IP }}"
        SSH_PORT=2699

         if [[ $DJANGO_ENV == "qa" ]]; then
          PROJECT_DIR="/home/jeet/backendproject/backendqa/thunder/backend"
          SERVICE_NAME="qa.thunder.jeethack.com.gunicorn"
        elif [[ $DJANGO_ENV == "staging" ]]; then
          PROJECT_DIR="/home/jeet/backendproject/backendstag/thunder/backend"
          SERVICE_NAME="staging.thunder.jeethack.com.gunicorn"
        elif [[ $DJANGO_ENV == "production" ]]; then
          PROJECT_DIR="/home/jeet/backendproject/backendprod/thunder/backend"
          SERVICE_NAME="thunder.jeethack.com.gunicorn"
        fi

        ssh -p $SSH_PORT $SSH_HOST <<EOF
          cd $PROJECT_DIR
          git pull origin ${{ github.ref_name }}
          source thunder$DJANGO_ENV/bin/activate
          pip install -r requirements.txt
          python manage.py migrate --settings=backend.settings.$DJANGO_ENV
          python manage.py collectstatic --noinput --settings=backend.settings.$DJANGO_ENV
          sudo systemctl restart $SERVICE_NAME
          sudo systemctl restart nginx
        EOF
